### ISSUE TITLE
推理后脸部抖动很厉害，原版不会，不知道为什么~

### ISSUE THREAD

**Issue by SakuraMaiii** [IronSpiderMan/MuseTalkPlus#1]
https://github.com/user-attachments/assets/13636ed0-6126-4db4-b3cb-aa201aa1f7aa

https://github.com/user-attachments/assets/d75b7f88-e272-4731-8826-ea687a677bc6

**Comment by IronSpiderMan** [comment]
训练的和推理的代码都在原版的基础上做了修改。目前还在调试中，还没有开发完成，完成后会在readme更新详细信息。

**Comment by SakuraMaiii** [comment]
> 训练的和推理的代码都在原版的基础上做了修改。目前还在调试中，还没有开发完成，完成后会在readme更新详细信息。

持续关注~兹拉

**Comment by IronSpiderMan** [comment]
> 训练的和推理的代码都在原版的基础上做了修改。目前还在调试中，还没有开发完成，完成后会在readme更新详细信息。

目前更新的代码已经不再抖动了

**Comment by SakuraMaiii** [comment]
> > 训练的和推理的代码都在原版的基础上做了修改。目前还在调试中，还没有开发完成，完成后会在readme更新详细信息。
> 
> 目前更新的代码已经不再抖动了

好的，兹拉
