### ISSUE TITLE
请问一下，我下载项目后查看发现缺少了一部分代码，是不是有遗漏提交，比如MuseTalkModel、PositionalEncoding、whisper等

### ISSUE THREAD

**Issue by LvHuaiSheng** [IronSpiderMan/MuseTalkPlus#2]
请问一下，我下载项目后查看发现缺少了一部分代码，是不是有遗漏提交，比如MuseTalkModel、PositionalEncoding、whisper等

**Comment by IronSpiderMan** [comment]
目前还在开发中，今天晚上会更新一下缺失的部分以及依赖情况。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月13日(星期五) 上午9:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [IronSpiderMan/MuseTalkPlus] 请问一下，我下载项目后查看发现缺少了一部分代码，是不是有遗漏提交，比如MuseTalkModel、PositionalEncoding、whisper等 (Issue #2)














 
请问一下，我下载项目后查看发现缺少了一部分代码，是不是有遗漏提交，比如MuseTalkModel、PositionalEncoding、whisper等

**Comment by IronSpiderMan** [comment]
> 请问一下，我下载项目后查看发现缺少了一部分代码，是不是有遗漏提交，比如MuseTalkModel、PositionalEncoding、whisper等

确实部分已经提交。其中whisper是openai-whisper模块

**Comment by LvHuaiSheng** [comment]
> > 请问一下，我下载项目后查看发现缺少了一部分代码，是不是有遗漏提交，比如MuseTalkModel、PositionalEncoding、whisper等
> 
> 缺失部分已经提交。其中whisper是openai-whisper模块

感谢作者，我再次尝试一下

**Comment by LvHuaiSheng** [comment]
请问目前是不是只有训练代码可用，server和webui还是缺少了部分代码，另外server中webSocket对应的页面处理有相关示例或代码吗

**Comment by IronSpiderMan** [comment]
> 请问目前是不是只有训练代码可用，server和webui还是缺少了部分代码，另外server中webSocket对应的页面处理有相关示例或代码吗

这部分代码还在完善中，完善好了会更新README.md文档。

**Comment by LvHuaiSheng** [comment]
> > 请问目前是不是只有训练代码可用，server和webui还是缺少了部分代码，另外server中webSocket对应的页面处理有相关示例或代码吗
> 
> 这部分代码还在完善中，完善好了会更新README.md文档。

好的，非常期待~

**Comment by IronSpiderMan** [comment]
> > > 请问目前是不是只有训练代码可用，server和webui还是缺少了部分代码，另外server中webSocket对应的页面处理有相关示例或代码吗
> > 
> > 
> > 这部分代码还在完善中，完善好了会更新README.md文档。
> 
> 好的，非常期待~

有改进思路也可以提，目前还存在许多不足的地方。

**Comment by LvHuaiSheng** [comment]
大佬有交流群吗，测试结果抖动比较厉害 ，我看有个issues #1 已经修复这个问题了，是不是最新的代码调整了还没做兼容，测试效果如下：

https://github.com/user-attachments/assets/f2db5fe8-c1da-4446-813b-691c30f7055f
